#default config.yml
#Infractions Configuration File
#Global Settings
motd: true
save_interval_seconds: 30
kick_on_cite: false
ban_at_score: 5
require_proof: false
#Define Infraction Levels
level_1:
  - flying
  - sm-hacking
  - sm-griefing
level_2:
  - advertising
  - duping
  - immaturity
level_3:
  - griefing
  - disrespect
  - racism
  - bullying
level_4:
  - spamming
  - team-griefing
level_5:
  - lg-hacking
  - lg-griefing
#SQL Settings
MySQL: true
SQLport: 3306
SQLusername: root
SQLhostname: localhost
SQLpassword: ''
SQLdatabase: minecraft