name: Infractions
main: com.legit2.hqm.Infractions.Infractions
version: 0.1
description: Police your server with specific rules; give players a second or third chance before they are banned.
author: HmmmQuestionMark
commands:
    infractions:
        description: Important information.
    cite:
        description: Cite a player with an infraction.
        usage: /cite <player> <infraction> [proof-url]
        permission: infractions.mod
    uncite:
        description: Remove an infraction from a player.
        usage: /uncite <player> <key>
    history:
        description: Check a player's infraction history.
        usage: /history <player>
permissions:
    infractions.mod:
        description: Gives access to all Inferno commands
        default: op