#default config.yml
#Infractions Configuration File
#Global Settings
update: true
motd: true
save_interval_seconds: 30
kick_on_cite: false
ban: true
ban_at_score: 5
require_proof: false
virtue_value: -1
bitly:
    use: false
    user: '' #Sign-up for bit.ly
    key: ''
#Define Infraction Levels
level_1:
  - flying
  - sm-hacking
  - sm-griefing
level_2:
  - advertising
  - duping
  - immaturity
level_3:
  - griefing
  - disrespect
  - racism
  - bullying
level_4:
  - spamming
  - team-griefing
level_5:
  - lg-hacking
  - lg-griefing
virtues:
  - helping-admin
  - fixing-grief
  - reporting-hacks
#Define Chat Scores
chat_score_5: '&7[&cBANNED&7]' #Banned
chat_score_4: '&7[&6:(&7]' #Almost banned
chat_score_3: '&7[&6:\&7]' #Eh...
chat_score_2: '&7[&2:)&7]' #Alright
chat_score_1: '&7[&2:D&7]' #Perfect
chat_score_ignore: '&7[&3:3&7]' #Plugin ignores this player