name: Infractions
main: com.censoredsoftware.Infractions.Infractions
version: ${project.version}
description: Police your server with specific rules; give players a second or third chance before they are banned.
author: HmmmQuestionMark
commands:
    infractions:
        description: Important information.
    virtues:
        description: Important information.
    cite:
        description: Cite a player with an infraction.
        usage: /cite <player> <infraction> [proof-url]
        permission: infractions.mod
    uncite:
        description: Remove an infraction from a player.
        usage: /uncite <player> <key>
    history:
        description: Check a player's infraction history.
        usage: /history [player]
    clearhistory:
        description: Clear a player's infraction history.
        usage: /clearhistory <player>
        permission: infractions.clearhistory
permissions:
    infractions.ignore:
        default: false
    infractions.banexempt:
        default: false
    infractions.mod:
        description: Gives access to all Inferno commands
        default: op
    infractions.maxscore.1:
        default: false
    infractions.maxscore.2:
        default: false
    infractions.maxscore.3:
        default: false
    infractions.maxscore.4:
        default: false
    infractions.maxscore.5:
        default: false
    infractions.maxscore.6:
        default: false
    infractions.maxscore.7:
        default: false
    infractions.maxscore.8:
        default: false
    infractions.maxscore.9:
        default: false
    infractions.maxscore.10:
        default: false
    infractions.maxscore.11:
        default: false
    infractions.maxscore.12:
        default: false
    infractions.maxscore.13:
        default: false
    infractions.maxscore.14:
        default: false
    infractions.maxscore.15:
        default: false
    infractions.maxscore.16:
        default: false
    infractions.maxscore.17:
        default: false
    infractions.maxscore.18:
        default: false
    infractions.maxscore.19:
        default: false
    infractions.maxscore.20:
        default: false
    infractions.*:
        default: false
    infractions.clearhistory:
        default: op